#Create a new task
POST http://localhost:3333/api/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Title for the article",
  "description": "Come up with a title for the article Come up with a title for the article Come up with a title for the article",
  "price": 1000,
  "address": "Komarovo, d.40",
  "deadline": "18-01-2022",
  "category": "service",
  "city": "Moscow",
  "image": ""
}

###
# Get all posts and filtres
GET http://localhost:3333/api/posts?sortDirection=desc&category=1,2&limit=2&page=1 HTTP/1.1

###

# Get task by ID
GET http://localhost:3333/api/tasks/8ff1eefc-b332-44ed-801d-39738a041e9f HTTP/1.1

###

# Delete task by ID
DELETE http://localhost:3333/api/tasks/8ff1eefc-b332-44ed-801d-39738a041e9f HTTP/1.1

###
